name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [16.x]
      steps:
        - name: install modules
          run: npm install
        - name: run lint
          run: npm run lint
        - name: build project
          run: npm run build
        - name: test project
          run: npm run test